/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.jlangvand.idatt2104.udp.utilities;

import no.jlangvand.idatt2104.udp.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
