/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.jlangvand.idatt2104.udp.app;

import static no.jlangvand.idatt2104.udp.utilities.MathExpressionParser.parse;

import java.io.IOException;
import java.io.PrintStream;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.SocketException;


public class App {
    private DatagramPacket packet;
    private static final PrintStream out = System.out;
    private static final int packetLength = 128;
    private byte[] buf;
    private String request;
    private String response;

    public static void main(String[] args) {
        out.println("Starting server");
        new App().udpListener();
    }
    
    /*
     * Open a UDP socket and wait for incoming packets.
     *
     * Upon receiving a packet, parse the contents and return the result.    
     */
    public void udpListener() {
        try (DatagramSocket socket = new DatagramSocket(2021)) {
            for (;;) {
                buf = new byte[packetLength];
                packet = new DatagramPacket(buf, buf.length);
                socket.receive(packet);
                request = new String(buf, 0, buf.length);
                response = parse(request);
                packet.setData(response.getBytes());
                socket.send(packet);
            }
        } catch (SocketException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
