/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.jlangvand.idatt2104.udp.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
